export HISTCONTROL=ignoreboth:erasedups
export PAGER=less
export PATH=~/Binaries:$PATH
umask 0026

export BROWSER=firefox
export EDITOR=nano
export GDK_CORE_DEVICE_EVENTS=1

if test `tty` = /dev/tty1
then source ~/.bashrc
else startx
fi
