export HISTCONTROL=ignoreboth:erasedups
export PAGER=less
export PATH=~/Binaries:$PATH
umask 0026

if test `hostname` = cleome
then startx
else
	if test $TERM = screen
	then source ~/.bashrc
	else tmux attach || tmux
	fi
fi
