#!/bin/sh

for x in /etc/X11/xinit/xinitrc.d/*sh
do . "$x"
done

export GTK_USE_PORTAL=1
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

xrdb -merge ~/.Xresources
xwallpaper --maximize wallpaper &
ibus-daemon -xdr
dunst -font 'Sans 16' &
dbus-launch sxhkd -m -1 &
emacs --daemon

if test "$HOSTNAME" = cleome
then
	setxkbmap slatin
	redshift-service &
	unclutter --timeout 1 &
	xrandr --output HDMI-1 --rotate left
else
	xrandr --output HDMI-1 --primary --mode 1920x1080 --pos 1080x533 --rotate normal --output HDMI-2 --off --output DP-1 --mode 1920x1080 --pos 0x0 --rotate left --output HDMI-3 --off
	xinput set-button-map 14 3 2 1
	xinput set-prop 14 314 1
	xinput set-prop 14 327 1
	picom &
fi

exec dbus-launch dwm
#exec dbus-launch xterm
