#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]
then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh
	do [ -x "$f" ] && . "$f"
	done
	unset f
fi

xrdb -merge ~/.Xresources
dunst -font 'Sans 16' &
dbus-launch sxhkd -m -1 &
#emacs --daemon
xwallpaper --maximize wallpaper &

case `hostname` in
	cleome)
		setxkbmap slatin
		redshift-service &
		unclutter --timeout 1 &
		;;

	ilus|lilina)
		setxkbmap -layout vas,vasgr -variant modifiers,modifiers -option grp:win_space_toggle
		;;

	IT09)
		setxkbmap -layout slatin,sgreek -option grp:win_space_toggle
		xinput set-button-map 14 3 2 1
		xinput set-prop 14 315 1
		xinput set-prop 14 307 1
		picom &
		;;
esac

rm /tmp/dwm.fifo
exec dbus-launch dwm
#exec dbus-launch xterm
