#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]
then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh
	do [ -x "$f" ] && . "$f"
	done
	unset f
fi

xrdb -merge ~/.Xresources
dunst -font 'Sans 16' &
dbus-launch sxhkd -m -1 &
emacs --daemon
xwallpaper --maximize wallpaper &

case `hostname` in
	cleome)
		setxkbmap slatin
		redshift-service &
		unclutter --timeout 1 &
		;;

	ilus)
		setxkbmap -layout vas,vasgr -variant modifiers,modifiers -option grp:win_space_toggle
		;;

	lilina)
		setxkbmap -layout vas,vasgr -variant modifiers,modifiers -option grp:win_space_toggle
		picom &
		;;
esac

rm /tmp/dwm.fifo
exec dbus-launch dwm
#exec dbus-launch xterm
