#!/bin/sh

sxhkd &

options='osu-stable
steam
xterm
exit'

function run_an_app() {
        app=$(echo "$options" | dmenu -l -1 -fn 'Sans-32')
	if test -z "$app"
	then exit
	else $app
	fi
}

while true ; do run_an_app ; done
