#!/bin/dash

xrdb -merge ~/.Xresources

# keyboard configuration
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=xim
ibus-daemon -xd
setxkbmap us -option compose:caps,shift:both_capslock_cancel,ctrl:swap_rwin_rctrl

redshift_service &
dunst -font "Sans 16" &
feh --bg-fill wallpaper &
unclutter --timeout 1 &
bar &
dbus-launch sxhkd &
#dbus-launch openbox
dbus-launch dwm-loop
