#!/bin/sh

export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=xim

xrdb -merge ~/.Xresources
setxkbmap us -option compose:caps,shift:both_capslock
#compton &
feh --bg-fill wallpaper &
dunst &
tint2 &
ibus-daemon -xd
emacs --daemon
dbus-launch openbox
