#!/bin/sh

xrdb -merge ~/.Xresources

export GTK_USE_PORTAL=1
# keyboard configuration
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=xim
ibus-daemon -xdr
xset r rate 180
xkb:vu::eng

redshift-service &
dunst -font "Sans 16" &
feh --bg-fill wallpaper &
unclutter --timeout 1 &
bar &
unclutter &
dbus-launch sxhkd -m -1 &
xrandr -s 1920x1080
VBoxClient --clipboard
emacs --daemon
dbus-launch dwm-loop
