#!/bin/sh

# application spawners
riverctl map normal Super 1 spawn kitty
riverctl map normal Super D spawn bemenu-run

riverctl map normal Super Q close
riverctl map normal Super+Shift Q exit

# window management
riverctl map normal Super K focus-view next
riverctl map normal Super L focus-view previous
riverctl map normal Super+Shift K swap next
riverctl map normal Super+Shift L swap previous
riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super Return zoom

# layout management
riverctl map normal Super J send-layout-cmd rivertile 'main-ratio -0.05'
riverctl map normal Super Semicolon send-layout-cmd rivertile 'main-ratio +0.05'
riverctl map normal Super+Shift J send-layout-cmd rivertile 'main-count -1'
riverctl map normal Super+Shift Semicolon send-layout-cmd rivertile 'main-count +1'

riverctl map normal Super+Control J send-layout-cmd rivertile 'main-location left'
riverctl map normal Super+Control K send-layout-cmd rivertile 'main-location bottom'
riverctl map normal Super+Control L send-layout-cmd rivertile 'main-location top'
riverctl map normal Super+Control Semicolon send-layout-cmd rivertile 'main-location right'

# workspace management
riverctl map normal Super U set-focused-tags $((1 << 0))
riverctl map normal Super I set-focused-tags $((1 << 1))
riverctl map normal Super O set-focused-tags $((1 << 2))
riverctl map normal Super P set-focused-tags $((1 << 3))
riverctl map normal Super+Shift U set-view-tags $((1 << 0))
riverctl map normal Super+Shift I set-view-tags $((1 << 1))
riverctl map normal Super+Shift O set-view-tags $((1 << 2))
riverctl map normal Super+Shift P set-view-tags $((1 << 3))

# pointer configuration
for x in `riverctl list-inputs | grep pointer`
do
	riverctl input $x left-handed enabled
	riverctl input $x natural-scroll enabled
done

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

riverctl default-layout rivertile
rivertile
