export HISTCONTROL=ignoreboth:erasedups
export BROWSER=firefox
export EDITOR=emacsclient
export PAGER=less
export PATH=~/Binaries:$PATH
export GDK_CORE_DEVICE_EVENTS=1

umask 0026

if ps -A | grep Xorg
then
	source ~/.bashrc
else
	exec startx
fi
