export PATH=~/Binaries:$PATH
export HISTCONTROL=ignoreboth:erasedups
export BROWSER=firefox
export EDITOR=gvimf
export SUDO_EDITOR=emacsc
export PAGER=less

if test -z "$DISPLAY" && test -n "$XDG_VTNR" && test "$XDG_VTNR" -eq 1
then
	exec startx
elif (test -n "$XDG_VTNR" && test "$XDG_VTNR" -eq 2) ||
     (test -n "$SSH_CLIENT" || test -n "$SSH_TTY")
then
	screen -xRR VAS
else
	source ~/.bashrc
fi
