;; -*- lexical-binding: t -*-
(defun vi-on() (interactive)
	(vi-mode 1)
	(setq cursor-type 'box))

(defun vi-off() (interactive)
	(vi-mode -1)
	(setq cursor-type 'bar))

(setq vi-mode-map (make-sparse-keymap))
(define-key vi-mode-map (kbd "x") 'execute-extended-command)
(define-key vi-mode-map (kbd "X") 'eval-expression)
(define-key vi-mode-map (kbd "c") 'kill-whole-line)
(define-key vi-mode-map (kbd "C") 'kill-line)
(define-key vi-mode-map (kbd "d") 'backward-kill-word)
(define-key vi-mode-map (kbd "D") 'kill-word)
(define-key vi-mode-map (kbd "m") 'indent-line-or-region)
(define-key vi-mode-map (kbd "M") 'unindent-line-or-region)
(define-key vi-mode-map (kbd "j") 'join-line)
(define-key vi-mode-map (kbd "J") 'comment-or-uncomment-region)
(define-key vi-mode-map (kbd "q") (lambda() (interactive) (kill-this-buffer) (vi-on)))
(define-key vi-mode-map (kbd "Q") 'save-buffers-kill-terminal)
(define-key vi-mode-map (kbd "w") 'forward-word)
(define-key vi-mode-map (kbd "W") 'forward-whitespace)
(define-key vi-mode-map (kbd "u") 'backward-word)
(define-key vi-mode-map (kbd "U") 'backward-whitespace)
(define-key vi-mode-map (kbd "v") 'goto-line)
(define-key vi-mode-map (kbd ";") (lambda() (interactive) (end-of-line) (insert-char #x3B)))
(define-key vi-mode-map (kbd "`") 'eshell)

(define-key vi-mode-map (kbd "r") 'zap-up-to-char)
(define-key vi-mode-map (kbd "R") 'zap-up-to-char-backward)
(define-key vi-mode-map (kbd "s") (lambda() (interactive) (if (use-region-p) (deactivate-mark) (call-interactively 'set-mark-command))))
(define-key vi-mode-map (kbd "S") (lambda() (interactive) (beginning-of-line) (call-interactively 'set-mark-command) (forward-line)))
(define-key vi-mode-map (kbd "t") 'quick-goto-char)
(define-key vi-mode-map (kbd "T") 'quick-goto-char-backward)
(define-key vi-mode-map (kbd "n") 'backspace-or-unindent)
(define-key vi-mode-map (kbd "N") 'delete-forward-char)
(define-key vi-mode-map (kbd "h") 'scroll-up-command)
(define-key vi-mode-map (kbd "H") 'scroll-down-command)
(define-key vi-mode-map (kbd "y") 'isearch-repeat-forward)
(define-key vi-mode-map (kbd "Y") 'isearch-repeat-backward)
(define-key vi-mode-map (kbd "i") 'left-char)
(define-key vi-mode-map (kbd "I") 'beginning-of-line-text)
(define-key vi-mode-map (kbd "e") 'next-line)
(define-key vi-mode-map (kbd "E") 'forward-paragraph)
(define-key vi-mode-map (kbd "o") 'previous-line)
(define-key vi-mode-map (kbd "O") 'backward-paragraph)
(define-key vi-mode-map (kbd "a") 'right-char)
(define-key vi-mode-map (kbd "A") 'end-of-line)

(define-key vi-mode-map (kbd "z") 'undo)
(define-key vi-mode-map (kbd "Z") 'keyboard-quit)
(define-key vi-mode-map (kbd "f") 'find-file)
(define-key vi-mode-map (kbd "F") 'quick-find-file)
(define-key vi-mode-map (kbd "g") 'beginning-of-buffer)
(define-key vi-mode-map (kbd "G") 'end-of-buffer)
(define-key vi-mode-map (kbd "l") 'line-below)
(define-key vi-mode-map (kbd "L") 'line-above)
(define-key vi-mode-map (kbd "k") 'kmacro-start-macro)
(define-key vi-mode-map (kbd "K") 'kmacro-end-or-call-macro)
(define-key vi-mode-map (kbd "b") 'ido-switch-buffer)
(define-key vi-mode-map (kbd "B") 'save-buffer)
(define-key vi-mode-map (kbd "p") 'yank)
(define-key vi-mode-map (kbd "P") 'kill-ring-save)
(define-key vi-mode-map (kbd ".") 'repeat)
(define-key vi-mode-map (kbd "/") 'isearch-forward)
(define-key vi-mode-map (kbd "?") 'isearch-backward)
(define-key vi-mode-map (kbd "SPC") 'vi-off)
(define-key vi-mode-map (kbd "<escape>") 'keyboard-quit)
(define-key vi-mode-map (kbd "(") (lambda() (interactive) (next-buffer) (vi-on)))
(define-key vi-mode-map (kbd ")") (lambda() (interactive) (previous-buffer) (vi-on)))
(define-key vi-mode-map (kbd "<tab>") (lambda() (interactive) (switch-to-buffer nil) (vi-on)))

(define-key vi-mode-map (kbd "' v p") 'variable-pitch-mode)
(define-key vi-mode-map (kbd "' e a") (lambda() (interactive) (find-file (concat user-emacs-directory "/abbrev_defs"))))
(define-key vi-mode-map (kbd "' e i") (lambda() (interactive) (find-file user-init-file)))
(define-key vi-mode-map (kbd "' i t") 'toggle-indent-tabs)
(define-key vi-mode-map (kbd "' m m") 'markdown-mode)
(define-key vi-mode-map (kbd "' f r") 'french)
(define-key vi-mode-map (kbd "' c m") 'cmark)
(define-key vi-mode-map (kbd "' s t") 'spaces-to-tabs)
(define-key vi-mode-map (kbd "' e r") 'eval-region)
(define-key vi-mode-map (kbd "' s s") 'delete-other-windows)
(define-key vi-mode-map (kbd "' i b") 'ibuffer)
(define-key vi-mode-map (kbd "' c w") 'count-words)
(define-key vi-mode-map (kbd "' A") 'mark-whole-buffer)
(define-key vi-mode-map (kbd "' q w") (lambda() (interactive) (split-window-horizontally) (split-window-horizontally) (balance-windows) (follow-mode)))

(define-minor-mode vi-mode
	"Ghetto vi mode"
	:lighter " vi"
	:keymap 'vi-mode-map)
